# Generated by Django 4.0.3 on 2022-04-12 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapis.profile'),
        ),
    ]
