# Generated by Django 4.0.3 on 2022-04-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0002_alter_cartproduct_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allorder',
            name='selOrderStatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allorder',
            name='status',
            field=models.CharField(default='Pendiing', max_length=100),
        ),
    ]
