# Generated by Django 4.0.3 on 2022-04-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0002_allorder_currentorder_successorder_cancelorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='delTime',
            field=models.CharField(default='AnyTime', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
