# Generated by Django 4.0.3 on 2022-04-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0003_alter_allorder_selorderstatus_alter_allorder_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancelorder',
            old_name='orderSeller',
            new_name='upload',
        ),
        migrations.RemoveField(
            model_name='cancelorder',
            name='orderUser',
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='cancelby',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
