# Generated by Django 4.0.3 on 2022-04-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0004_rename_orderseller_cancelorder_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelorder',
            name='upload',
        ),
    ]
