# Generated by Django 4.0.3 on 2022-04-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0005_remove_cancelorder_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cancelorder',
            name='ammount',
        ),
        migrations.RemoveField(
            model_name='cancelorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cancelorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cancelorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cancelorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cancelorder',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='cancelorder',
            name='shipPrice',
        ),
        migrations.RemoveField(
            model_name='cancelorder',
            name='totalAmmount',
        ),
    ]
